version: '3.3'
services:
  rtm-shopping-list-printer:
    container_name: shopping-list
    image: rtm-shopping-list-printer
    ports:
      - "5000:3001"
    environment:
      LOG_LEVEL: 20 #Debug = 10, Info = 20, Warning = 30, Error = 40, Critical = 50
      API_KEY: myApiKey123
      SHARED_SECRET: mySharedSecret123
      FROB: myFrob123 #The frob will be printed in the console after the first start with a valid api key and secret. Put that in here and restart.
      AUTH_TOKEN: myAuthToken123 #This will be given to you after you restarted with a valid and authenticated frob. Put that in here and restart once more.
      ACTIVE_LIST: 'Shopping list' #The name of your shopping list
      LOG_SENSITIVE: 0 #If set to 1, sensitive data like the api key, frob or auth token might be printed to the console.
      BASIC_AUTH_USERNAME: "username" #The username for the http basic auth
      BASIC_AUTH_PASSWORD_HASH: "scrypt:32768:8:1$2aRMNwwbRB4MhCEb$f6e865a3213e188ee06866e060f0671bf65704d3fb7f41d901088972027f3038707a86c4f1c95f985e8944787290600d6505c16597b9675d6aeaf342f269f45a" #scrypt password hash for "hello". See the readme for instructions on how to get the hash
      BASIC_AUTH_PASSWORD: "password" #The password for the http basic auth. Use the password hash instead, this is not all that secure!
    restart: unless-stopped
